<?php

namespace App\Repository;

/**
 * HashtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashtagRepository extends \Doctrine\ORM\EntityRepository
{
}
