<?php

namespace PBG\Repository;

/**
 * VoiceMemo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoiceMemoRepository extends \Doctrine\ORM\EntityRepository
{
}
